// src/components/PlayerCard.tsx
import { useSortable } from '@dnd-kit/sortable';
import { CSS } from '@dnd-kit/utilities';
import { ArrowLeft } from 'lucide-react';

interface Player {
  id: number;
  name: string;
  number: string;
  position: string;
}

interface PlayerCardProps {
  player: Player;
  onRemove: () => void;
}

export default function PlayerCard({ player, onRemove }: PlayerCardProps) {
  const {
    attributes,
    listeners,
    setNodeRef,
    transform,
    transition,
    isDragging,
  } = useSortable({ id: player.id });

  const style = {
    transform: CSS.Transform.toString(transform),
    transition,
    opacity: isDragging ? 0.5 : 1,
  };

  return (
    <div
      ref={setNodeRef}
      style={style}
      {...attributes}
      {...listeners}
      className="bg-white rounded-lg border border-gray-200 p-4 cursor-move hover:border-black transition-colors"
    >
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="w-8 h-8 bg-gray-100 rounded-full flex items-center justify-center text-sm font-medium">
            {player.number}
          </div>
          <div>
            <p className="font-medium">{player.name}</p>
            <p className="text-sm text-gray-500">{player.position}</p>
          </div>
        </div>
        <button
          onClick={onRemove}
          className="p-2 text-red-500 hover:bg-red-50 rounded-full transition-colors"
          title="Remove from lineup"
        >
          <ArrowLeft className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}

// src/components/players/PlayerCard.vue
<template>
  <div class="bg-white rounded-lg border border-gray-200 p-4 hover:border-black transition-colors">
    <div class="flex items-center gap-4">
      <div class="w-12 h-12 bg-gray-100 rounded-full flex items-center justify-center text-lg font-medium">
        {{ player.number }}
      </div>
      <div class="flex-1">
        <h3 class="font-medium">{{ player.name }}</h3>
        <p class="text-sm text-gray-500">{{ player.position }}</p>
        <div class="flex items-center gap-1 mt-1 text-sm text-gray-500">
          <ClockIcon class="w-4 h-4" />
          <span>{{ player.total_minutes }} min played</span>
        </div>
      </div>
      <div class="flex gap-2">
        <button
          @click="$emit('edit', player)"
          class="p-2 text-gray-400 hover:text-blue-500 rounded-full hover:bg-blue-50 transition-colors"
          title="Edit player"
        >
          <Edit2Icon class="w-4 h-4" />
        </button>
        <button
          @click="$emit('delete', player)"
          class="p-2 text-gray-400 hover:text-red-500 rounded-full hover:bg-red-50 transition-colors"
          title="Delete player"
        >
          <Trash2Icon class="w-4 h-4" />
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { Player } from '@/types';

defineProps<{
  player: Player;
}>();

defineEmits<{
  (e: 'edit', player: Player): void;
  (e: 'delete', player: Player): void;
}>();
</script>

<script lang="ts">
export default {
  name: 'PlayerCard'
}
</script>
