// src/components/VideoPlayer.tsx
import React, { useRef, useEffect, useState } from 'react';
import { Trash2, Maximize2, Minimize2, Settings2, Plus, Pencil, Eraser } from 'lucide-react';
import toast from 'react-hot-toast';

interface VideoPlayerProps {
  videoUrl: string;
  onFileChange: (file: File) => void;
  onRemove?: () => void;
  showRemoveButton?: boolean;
  onAddAction: (timestamp: number) => Promise<{ created_at: string }>;
  initialMarkers?: { timestamp: number; date: string; }[];
}

interface Marker {
  timestamp: number;
  date: string;
}

export default function VideoPlayer({ 
  videoUrl, 
  onFileChange, 
  onRemove,
  showRemoveButton = true,
  onAddAction,
  initialMarkers = []
}: VideoPlayerProps) {
  const videoRef = useRef<HTMLVideoElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [duration, setDuration] = useState(0);
  const [showTools, setShowTools] = useState(false);
  const [markers, setMarkers] = useState<Marker[]>(initialMarkers);
  const [isDrawing, setIsDrawing] = useState(false);
  const [isDrawMode, setIsDrawMode] = useState(false);
  const [lastPoint, setLastPoint] = useState<{ x: number; y: number } | null>(null);

  useEffect(() => {
    setMarkers(initialMarkers);
  }, [initialMarkers]);

  useEffect(() => {
    const handleFullscreenChange = () => {
      setIsFullscreen(Boolean(document.fullscreenElement));
      if (!document.fullscreenElement) {
        setShowTools(false);
        setIsDrawMode(false);
      }
    };

    document.addEventListener('fullscreenchange', handleFullscreenChange);
    return () => document.removeEventListener('fullscreenchange', handleFullscreenChange);
  }, []);

  useEffect(() => {
    const video = videoRef.current;
    if (video) {
      const handleLoadedMetadata = () => {
        setDuration(video.duration);
      };
      video.addEventListener('loadedmetadata', handleLoadedMetadata);
      return () => video.removeEventListener('loadedmetadata', handleLoadedMetadata);
    }
  }, [videoUrl]);

  useEffect(() => {
    if (isDrawMode && canvasRef.current) {
      const canvas = canvasRef.current;
      const container = containerRef.current;
      if (container) {
        canvas.width = container.clientWidth;
        canvas.height = container.clientHeight;
      }
    }
  }, [isDrawMode]);

  const handleFullscreen = async () => {
    if (!containerRef.current) return;

    try {
      if (!document.fullscreenElement) {
        await containerRef.current.requestFullscreen();
      } else {
        await document.exitFullscreen();
      }
    } catch (error) {
      console.error('Error toggling fullscreen:', error);
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      onFileChange(selectedFile);
    }
  };

  const handleAddAction = async (e: React.MouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    
    const video = videoRef.current;
    if (video) {
      try {
        const currentTime = video.currentTime;
        const response = await onAddAction(currentTime);
        
        const newMarker = {
          timestamp: currentTime,
          date: response.created_at
        };
        setMarkers(prev => [...prev, newMarker]);
        toast.success('Action added successfully');
      } catch (error) {
        toast.error('Failed to add action');
      }
    }
  };

  const seekToTime = (timestamp: number) => {
    const video = videoRef.current;
    if (video) {
      video.currentTime = timestamp;
    }
  };

  const startDrawing = (e: React.MouseEvent<HTMLCanvasElement>) => {
    if (!isDrawMode) return;
    const canvas = canvasRef.current;
    if (!canvas) return;

    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    setIsDrawing(true);
    setLastPoint({ x, y });
  };

  const draw = (e: React.MouseEvent<HTMLCanvasElement>) => {
    if (!isDrawing || !isDrawMode || !lastPoint) return;
    const canvas = canvasRef.current;
    if (!canvas) return;

    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const rect = canvas.getBoundingClientRect();
    const x = e.clientX - rect.left;
    const y = e.clientY - rect.top;

    ctx.beginPath();
    ctx.strokeStyle = '#00ff00';
    ctx.lineWidth = 3;
    ctx.lineCap = 'round';
    ctx.moveTo(lastPoint.x, lastPoint.y);
    ctx.lineTo(x, y);
    ctx.stroke();

    setLastPoint({ x, y });
  };

  const stopDrawing = () => {
    setIsDrawing(false);
    setLastPoint(null);
  };

  const clearCanvas = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
  };

  return (
    <div className="card overflow-hidden">
      <div 
        ref={containerRef} 
        className={`relative group bg-black ${isFullscreen ? 'h-screen flex flex-col' : ''}`}
      >
        <style>{`
          video::-webkit-media-controls-enclosure {
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
            width: 100%;
            padding: 0;
            margin-bottom: 10px;
          }

          video::-webkit-media-controls-panel {
            display: flex;
            flex-direction: column;
            justify-content: flex-end;
            width: 100%;
            padding: 0 12px;
            margin-bottom: 0;
          }

          video::-webkit-media-controls-timeline-container {
            width: 100%;
            margin: 0;
            padding-top: 5px;
          }

          video::-webkit-media-controls-timeline {
            width: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
          }

          video::-webkit-media-controls-volume-slider {
            margin: 0;
          }

          video::-webkit-media-controls-play-button {
            margin: 0;
          }
          
          .marker-overlay {
            position: absolute;
            bottom: 48px;
            left: 12px;
            right: 12px;
            height: 0;
            pointer-events: none;
          }
          
          .marker-overlay .marker {
            position: absolute;
            bottom: 0;
            transform: translateX(-50%);
            cursor: pointer;
            pointer-events: auto;
          }

          .marker-overlay .marker div {
            width: 10px;
            height: 10px;
            border: 1.5px solid #ef4444;
            border-radius: 50%;
            background: transparent;
          }

          .marker-overlay .marker:hover div {
            background: #ef4444;
            transition: background-color 0.2s;
          }
        `}</style>

        <video
          ref={videoRef}
          src={videoUrl}
          controls
          controlsList="nodownload nofullscreen"
          className={`${isFullscreen ? 'flex-1 h-[calc(100%-24px)]' : 'aspect-video'} w-full`}
        />

        {isDrawMode && (
          <canvas
            ref={canvasRef}
            className="absolute inset-0 cursor-crosshair"
            onMouseDown={startDrawing}
            onMouseMove={draw}
            onMouseUp={stopDrawing}
            onMouseLeave={stopDrawing}
          />
        )}
        
        {duration > 0 && (
          <div className="marker-overlay">
            {markers.map((marker, index) => (
              <div 
                key={index}
                className="marker"
                style={{ left: `${(marker.timestamp / duration) * 100}%` }}
                onClick={() => seekToTime(marker.timestamp)}
              >
                <div />
              </div>
            ))}
          </div>
        )}

        {isFullscreen && (
          <>
            <button
              onClick={() => setShowTools(!showTools)}
              className="absolute top-4 right-4 p-2 bg-blue-500 text-white rounded-lg opacity-0 group-hover:opacity-100 transition-opacity hover:bg-blue-600 shadow-lg hover:shadow-blue-500/50"
              title="Toggle tools"
            >
              <Settings2 className="w-5 h-5" />
            </button>

            <div className={`absolute top-4 right-16 flex gap-2 transition-all duration-200 ${showTools ? 'opacity-100' : 'opacity-0 pointer-events-none'}`}>
              <button
                onClick={handleAddAction}
                className="p-2 bg-blue-500 text-white rounded-lg flex items-center gap-2 hover:bg-blue-600 transition-colors shadow-lg hover:shadow-blue-500/50"
                title="Add action"
              >
                <Plus className="w-5 h-5" />
              </button>
              {isDrawMode ? (
                <button
                  onClick={() => {
                    setIsDrawMode(false);
                    clearCanvas();
                  }}
                  className="p-2 bg-red-500 text-white rounded-lg flex items-center gap-2 hover:bg-red-600 transition-colors shadow-lg hover:shadow-red-500/50"
                  title="Stop drawing"
                >
                  <Eraser className="w-5 h-5" />
                </button>
              ) : (
                <button
                  onClick={() => setIsDrawMode(true)}
                  className="p-2 bg-blue-500 text-white rounded-lg flex items-center gap-2 hover:bg-blue-600 transition-colors shadow-lg hover:shadow-blue-500/50"
                  title="Start drawing"
                >
                  <Pencil className="w-5 h-5" />
                </button>
              )}
              <button
                onClick={handleFullscreen}
                className="p-2 bg-blue-500 text-white rounded-lg flex items-center gap-2 hover:bg-blue-600 transition-colors shadow-lg hover:shadow-blue-500/50"
                title="Exit fullscreen"
              >
                <Minimize2 className="w-5 h-5" />
              </button>
            </div>
          </>
        )}

        {!isFullscreen && (
          <button
            onClick={handleFullscreen}
            className="absolute bottom-20 right-4 p-2 bg-blue-500 text-white rounded-lg opacity-0 group-hover:opacity-100 transition-opacity flex items-center gap-2 hover:bg-blue-600 shadow-lg hover:shadow-blue-500/50"
            title="Enter fullscreen"
          >
            <Maximize2 className="w-5 h-5" />
          </button>
        )}
      </div>

      {!isFullscreen && (
        <div className="p-4 border-t border-gray-200 flex items-center justify-between">
          <label className="btn inline-block cursor-pointer">
            Change Video
            <input
              type="file"
              accept="video/*"
              className="hidden"
              onChange={handleFileUpload}
            />
          </label>
          {showRemoveButton && onRemove && (
            <button
              onClick={onRemove}
              className="text-red-600 hover:text-red-700 p-2 rounded-full hover:bg-red-50 transition-colors"
              title="Remove video"
            >
              <Trash2 className="w-5 h-5" />
            </button>
          )}
        </div>
      )}
    </div>
  );
}

// src/components/VideoPlayer.vue
<template>
  <div class="card overflow-hidden">
    <div 
      ref="containerRef"
      :class="[
        'relative group bg-black',
        isFullscreen ? 'h-screen flex flex-col' : ''
      ]"
    >
      <video
        ref="videoRef"
        :src="props.videoUrl"
        controls
        controlsList="nodownload nofullscreen"
        :class="[
          isFullscreen ? 'flex-1 h-[calc(100%-24px)]' : 'aspect-video',
          'w-full',
          isDrawMode ? 'pointer-events-none' : ''
        ]"
      />

      

      <canvas
        v-if="isDrawMode"
        ref="canvasRef"
        class="absolute inset-0 cursor-crosshair"
        @mousedown="startDrawing"
        @mousemove="draw"
        @mouseup="stopDrawing"
        @mouseleave="stopDrawing"
      />

      <div class="marker-overlay">
        <div 
          v-for="(marker, index) in markers"
          :key="index"
          class="marker"
          :style="{ left: `${(marker.timestamp / duration) * 100}%` }"
          @click="seekToTime(marker.timestamp)"
          :title="marker.name"
        >
          <div />
        </div>
      </div>

      <div v-if="isFullscreen" class="absolute top-4 right-4 flex gap-2">
        <button
          @click="toggleDrawMode"
          class="p-2 bg-blue-500 text-white rounded-lg"
          :title="isDrawMode ? 'Stop drawing' : 'Start drawing'"
        >
          <component :is="isDrawMode ? EraserIcon : PencilIcon" class="w-5 h-5" />
        </button>
        <button
          @click="handleFullscreen"
          class="p-2 bg-blue-500 text-white rounded-lg"
          title="Exit fullscreen"
        >
          <Minimize2Icon class="w-5 h-5" />
        </button>
      </div>

      <button
        v-else
        @click="handleFullscreen"
        class="absolute bottom-20 right-4 p-2 bg-blue-500 text-white rounded-lg opacity-0 group-hover:opacity-100 transition-opacity"
        title="Enter fullscreen"
      >
        <Maximize2Icon class="w-5 h-5" />
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import { PencilIcon, EraserIcon, Maximize2Icon, Minimize2Icon } from 'lucide-vue-next';

const videoRef = ref<HTMLVideoElement | null>(null);
const canvasRef = ref<HTMLCanvasElement | null>(null);
const containerRef = ref<HTMLDivElement | null>(null);
const isDrawMode = ref(false);
const isDrawing = ref(false);
const lastPoint = ref<{ x: number; y: number } | null>(null);
const isFullscreen = ref(false);
const props = defineProps<{
  videoUrl: string;
  initialMarkers?: { timestamp: number; date: string; name: string }[];
}>();

const duration = ref(0);
const markers = ref(props.initialMarkers || []);

// Ajustar el tamaño del canvas cuando cambia el modo de dibujo
watch(isDrawMode, (newValue) => {
  if (newValue && containerRef.value && canvasRef.value) {
    const container = containerRef.value;
    const canvas = canvasRef.value;
    canvas.width = container.clientWidth;
    canvas.height = container.clientHeight;
  }
});

const startDrawing = (e: MouseEvent) => {
  if (!isDrawMode.value) return;
  const canvas = canvasRef.value;
  if (!canvas) return;

  const rect = canvas.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const y = e.clientY - rect.top;

  isDrawing.value = true;
  lastPoint.value = { x, y };
};

const draw = (e: MouseEvent) => {
  if (!isDrawing.value || !isDrawMode.value || !lastPoint.value) return;
  const canvas = canvasRef.value;
  if (!canvas) return;

  const ctx = canvas.getContext('2d');
  if (!ctx) return;

  const rect = canvas.getBoundingClientRect();
  const x = e.clientX - rect.left;
  const y = e.clientY - rect.top;

  ctx.beginPath();
  ctx.strokeStyle = '#00ff00'; // Color verde como en React
  ctx.lineWidth = 3; // Mismo grosor que en React
  ctx.lineCap = 'round';
  ctx.moveTo(lastPoint.value.x, lastPoint.value.y);
  ctx.lineTo(x, y);
  ctx.stroke();

  lastPoint.value = { x, y };
};

const stopDrawing = () => {
  isDrawing.value = false;
  lastPoint.value = null;
};

const toggleDrawMode = () => {
  isDrawMode.value = !isDrawMode.value;
  if (!isDrawMode.value) {
    clearCanvas();
  }
};

const clearCanvas = () => {
  const canvas = canvasRef.value;
  if (!canvas) return;
  const ctx = canvas.getContext('2d');
  if (!ctx) return;
  ctx.clearRect(0, 0, canvas.width, canvas.height);
};

// Ajustar el tamaño del canvas cuando cambia el tamaño de la ventana
onMounted(() => {
  window.addEventListener('resize', () => {
    if (isDrawMode.value && containerRef.value && canvasRef.value) {
      const container = containerRef.value;
      const canvas = canvasRef.value;
      canvas.width = container.clientWidth;
      canvas.height = container.clientHeight;
    }
  });

  if (videoRef.value) {
    videoRef.value.addEventListener('loadedmetadata', () => {
      duration.value = videoRef.value?.duration || 0;
    });
  }
});

const handleFullscreen = async () => {
  if (!containerRef.value) return;
  
  try {
    if (!document.fullscreenElement) {
      await containerRef.value.requestFullscreen();
      isFullscreen.value = true;
    } else {
      await document.exitFullscreen();
      isFullscreen.value = false;
    }
  } catch (error) {
    console.error('Error toggling fullscreen:', error);
  }
};

const seekToTime = (timestamp: number) => {
  if (videoRef.value) {
    videoRef.value.currentTime = timestamp;
  }
};
</script>

<style scoped>
canvas {
  pointer-events: all;
}

.marker-overlay {
  position: absolute;
  bottom: 68px;
  left: 12px;
  right: 12px;
  height: 0;
  pointer-events: none;
}

.marker {
  position: absolute;
  bottom: 0;
  transform: translateX(-50%);
  cursor: pointer;
  pointer-events: auto;
}

.marker div {
  width: 10px;
  height: 10px;
  border: 1.5px solid #ef4444;
  border-radius: 50%;
  background: transparent;
}

.marker:hover div {
  background: #ef4444;
  transition: background-color 0.2s;
}

/* Opcional: Si prefieres un tooltip personalizado en lugar del título nativo del navegador */
.marker:hover::after {
  content: attr(title);
  position: absolute;
  bottom: 100%;
  left: 50%;
  transform: translateX(-50%);
  padding: 4px 8px;
  background: rgba(0, 0, 0, 0.8);
  color: white;
  border-radius: 4px;
  font-size: 12px;
  white-space: nowrap;
  pointer-events: none;
}
</style>

<script lang="ts">
export default {
  name: 'VideoPlayer'
}
</script>
