// src/layouts/MainLayout.vue
```vue
<template>
  <div>
    <Header v-if="!isLoginPage && !isTeamPage" back-text="Go Back" />
    <slot></slot>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { useRoute } from 'vue-router';
import Header from '@/components/Header.vue';

const route = useRoute();

const isLoginPage = computed(() => route.path === '/login');
const isTeamPage = computed(() => route.path === '/');
</script>
```

// src/layouts/MainLayout.tsx
import { useLocation } from 'react-router-dom';
import Header from '../components/Header';

interface MainLayoutProps {
  children: React.ReactNode;
}

export default function MainLayout({ children }: MainLayoutProps) {
  const location = useLocation();
  const isLoginPage = location.pathname === '/login';
  const isTeamPage = location.pathname === '/';

  return (
    <>
      {!isLoginPage && !isTeamPage && <Header backText="Go Back" />}
      {children}
    </>
  );
}
